name: 'dbt_test'
version: '1.0.0'
config-version: 2

profile: 'dbt_test'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

seeds:
  +schema: seed_data

models:
  dbt_test:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  regions: {
    'Australia': 'au',
    'Europe': 'eu',
    'North America': 'na'
  }