dbt_test:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: dbt_database
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: dbt_role
      schema: analytics_dev
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: dbt_warehouse
    prod:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: dbt_database
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: dbt_role
      schema: analytics
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: dbt_warehouse
  target: dev