name: Deployment
on:
  push:
    branches: 
      - main
jobs:
  create-deployment-pr:
    name: Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set default identity
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
      - name: Create deployment PR
        run: |
          git fetch --unshallow
          git checkout -B production origin/production
          git checkout -b merge-main-into-production
          git rebase origin/main
          git push --set-upstream origin merge-main-into-production --force
          gh pr create -B production --title "Merge changes into production" --body "Created automatically"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}