name: Transformations
on:
  schedule:
    - cron: "30 */6 * * *" # at minute 30 past every 6th hour

  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

jobs:
  production-run:
    name: Production Run
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install Pipenv
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          pipenv install
      - name: Install dbt dependencies
        run: | 
          pipenv run dbt deps --target prod
      - name: Check ingestion warehouse status
        run: | 
          pipenv run dbt run-operation check_ingestion_warehouse_status --target prod
        env:
          INGESTION_WAREHOUSE: ${{ secrets.INGESTION_WAREHOUSE }}
#      - name: Test source freshness
#        if: ${{ success() }}
#        run: | 
#          pipenv run dbt source freshness
      - name: Run and test models
        if: ${{ success() }}
        run: |
          pipenv run dbt build --target prod
      - name: Generate documentation
        if: ${{ success() }}
        run: |
          pipenv run dbt docs generate --target prod
      - name: Cache manifest file
        uses: actions/cache/save@v4
        with:
          path: target/manifest.json
          key: manifest-${{ github.run_id }}
      - name: Cache catalog file
        uses: actions/cache/save@v4
        with:
          path: target/catalog.json
          key: catalog-${{ github.run_id }}
      - name: Cache index file
        uses: actions/cache/save@v4
        with:
          path: target/index.html
          key: index-${{ github.run_id }}
      - name: Send Slack notification
        if: ${{ failure() }}
        run: |
          curl ${{ secrets.SLACK_DBT_NOTIFICATION_WEBHOOK_URL }} \
            --request POST \
            --header 'Content-type: application/json' \
            --data \
              '{
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "${{ github.workflow }} job has failed"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "The latest *production* run of dbt was unsuccessful."
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Full logs available on GitHub"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Navigate to GitHub"
                      },
                      "style": "primary",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  }
                ]
              }'
  documentation-update:
    name: Update Documentation
    needs: production-run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout documentation branch
        uses: actions/checkout@v4
        with:
          ref: refs/heads/gh-pages
      - name: Restore manifest file
        uses: actions/cache/restore@v4
        with:
          path: target/manifest.json
          key: manifest-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Restore catalog file
        uses: actions/cache/restore@v4
        with:
          path: target/catalog.json
          key: catalog-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Restore index file
        uses: actions/cache/restore@v4
        with:
          path: target/index.html
          key: index-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Update documentation
        run: |
          rm -rf docs
          mv target docs
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add --force docs/manifest.json docs/catalog.json docs/index.html
          git commit -m "Update documentation"
          git push --set-upstream origin gh-pages 