name: Transformations
on:
  schedule:
    - cron: "30 */6 * * *" # at minute 30 past every 6th hour

  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

jobs:
  clear-cache:
    name: Clear cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clear manifest cache
        run: | 
          gh cache delete manifest
          gh cache delete catalog
          gh cache delete index
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  production-run:
    name: Production Run
    needs: clear-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install Pipenv
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          pipenv install
      - name: Install dbt dependencies
        run: pipenv run dbt deps --target prod
      - name: Run and test models
        run: pipenv run dbt build --target prod
      - name: Generate documentation
        run: pipenv run dbt docs generate --target prod
      - name: Cache manifest file
        uses: actions/cache/save@v3
        with:
          path: target/manifest.json
          key: manifest
      - name: Cache catalog file
        uses: actions/cache/save@v3
        with:
          path: target/catalog.json
          key: catalog
      - name: Cache index file
        uses: actions/cache/save@v3
        with:
          path: target/index.html
          key: index
  documentation-update:
    name: Update Documentation
    needs: production-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout documentation branch
        uses: actions/checkout@v4
        with:
          ref: refs/heads/gh-pages
      - name: Restore manifest file
        uses: actions/cache/restore@v3
        with:
          path: target/manifest.json
          key: manifest
          fail-on-cache-miss: true
      - name: Restore catalog file
        uses: actions/cache/restore@v3
        with:
          path: target/catalog.json
          key: catalog
          fail-on-cache-miss: true
      - name: Restore index file
        uses: actions/cache/restore@v3
        with:
          path: target/index.html
          key: index
          fail-on-cache-miss: true
      - name: Update documentation
        run: |
          mv target docs
          git config user.email "martin@chakarov.com"
          git config user.name "Martin"
          git add --force docs/manifest.json docs/catalog.json docs/index.html
          git commit -m "Update documentation"
          git push --set-upstream origin gh-pages 