name: Transformations
on:
  schedule:
    - cron: "30 */6 * * *" # at minute 30 past every 6th hour

  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

jobs:
  clear-cache:
    name: Clear manifest.json cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clear cache
        run: gh cache delete manifest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  production-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install Pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Pipenv dependencies
        run: pipenv install
      - name: Install dbt dependenciees
        run: pipenv run dbt deps --target prod
      - name: Run and test models
        run: pipenv run dbt build --target prod
      - name: Generate documentation
        run: pipenv run dbt docs generate
      - name: Cache manifest file
        uses: actions/cache/save@v3
        with:
          path: target/manifest.json
          key: manifest
      - name: Cache catalog file
        uses: actions/cache/save@v3
        with:
          path: target/catalog.json
          key: catalog
      - name: Cache index file
        uses: actions/cache/save@v3
        with:
          path: target/index.html
          key: index
  documentation-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete old gh-pages branch
        run: git branch -D gh-pages
      - name: Create a new gh-pages branch
        run: git checkout -b gh-pages
      - name: Restore manifest file
        uses: actions/cache/restore@v3
        with:
          path: target/manifest.json
          key: manifest
          fail-on-cache-miss: true
      - name: Restore catalog file
        uses: actions/cache/restore@v3
        with:
          path: target/catalog.json
          key: catalog
          fail-on-cache-miss: true
      - name: Restore index file
        uses: actions/cache/restore@v3
        with:
          path: target/index.html
          key: index
          fail-on-cache-miss: true